// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/crazyfrankie/douyin/app/sms/biz/repository"
	"github.com/crazyfrankie/douyin/app/sms/biz/repository/cache"
	"github.com/crazyfrankie/douyin/app/sms/biz/rpc"
	"github.com/crazyfrankie/douyin/app/sms/biz/rpc/server"
	"github.com/crazyfrankie/douyin/app/sms/biz/service"
	"github.com/crazyfrankie/douyin/app/sms/biz/service/memory"
)

// Injectors from wire.go:

func InitApp() *App {
	cmdable := InitRedis()
	codeCache := cache.NewCodeCache(cmdable)
	codeRepo := repository.NewCodeRepo(codeCache)
	v := InitSms()
	smsService := service.NewSmsService(codeRepo, v...)
	smsServer := server.NewSmsServer(smsService)
	rpcServer := rpc.NewSmsGRPCServer(smsServer)
	app := &App{
		RPCServer: rpcServer,
	}
	return app
}

// wire.go:

func InitSms() []service.SendService {
	my := memory.NewMemorySms()

	return []service.SendService{my}
}
