// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/crazyfrankie/douyin/app/feed/biz/repository"
	"github.com/crazyfrankie/douyin/app/feed/biz/repository/dao"
	"github.com/crazyfrankie/douyin/app/feed/biz/rpc"
	"github.com/crazyfrankie/douyin/app/feed/biz/rpc/client"
	"github.com/crazyfrankie/douyin/app/feed/biz/rpc/server"
	"github.com/crazyfrankie/douyin/app/feed/biz/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := InitDB()
	feedDao := dao.NewFeedDao(db)
	feedRepo := repository.NewFeedRepo(feedDao)
	userServiceClient := client.InitUserClient()
	favoriteServiceClient := client.InitFavoriteClient()
	commentServiceClient := client.InitCommentClient()
	feedService := service.NewFeedService(feedRepo, userServiceClient, favoriteServiceClient, commentServiceClient)
	videoServer := server.NewVideoServer(feedService)
	rpcServer := rpc.NewFeedRPCServer(videoServer)
	app := &App{
		RPCServer: rpcServer,
	}
	return app
}
