// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/crazyfrankie/douyin/app/comment/biz/repository"
	"github.com/crazyfrankie/douyin/app/comment/biz/repository/dao"
	"github.com/crazyfrankie/douyin/app/comment/biz/rpc"
	"github.com/crazyfrankie/douyin/app/comment/biz/rpc/client"
	"github.com/crazyfrankie/douyin/app/comment/biz/rpc/server"
	"github.com/crazyfrankie/douyin/app/comment/biz/service"
	"github.com/crazyfrankie/douyin/app/comment/ioc"
)

// Injectors from wire.go:

func InitApp() *ioc.App {
	db := ioc.InitDB()
	commentDao := dao.NewCommentDao(db)
	commentRepo := repository.NewCommentRepo(commentDao)
	filter := ioc.InitFilter()
	userServiceClient := client.InitUserClient()
	commentService := service.NewCommentService(commentRepo, filter, userServiceClient)
	commentServer := server.NewCommentServer(commentService)
	rpcServer := rpc.NewCommentRPCServer(commentServer)
	app := &ioc.App{
		RPCServer: rpcServer,
	}
	return app
}
