// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/crazyfrankie/douyin/app/relation/biz/repository"
	"github.com/crazyfrankie/douyin/app/relation/biz/repository/dao"
	"github.com/crazyfrankie/douyin/app/relation/biz/rpc"
	"github.com/crazyfrankie/douyin/app/relation/biz/rpc/client"
	"github.com/crazyfrankie/douyin/app/relation/biz/rpc/server"
	"github.com/crazyfrankie/douyin/app/relation/biz/service"
	"github.com/crazyfrankie/douyin/app/relation/ioc"
)

// Injectors from wire.go:

func InitApp() *ioc.App {
	db := ioc.InitDB()
	relationDao := dao.NewRelationDao(db)
	relationRepo := repository.NewRelationRepo(relationDao)
	userServiceClient := client.InitUserClient()
	relationService := service.NewRelationService(relationRepo, userServiceClient)
	relationServer := server.NewRelationServer(relationService)
	rpcServer := rpc.NewRelationRPCServer(relationServer)
	app := &ioc.App{
		RPCServer: rpcServer,
	}
	return app
}
