// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/crazyfrankie/douyin/app/favorite/biz/handler"
	"github.com/crazyfrankie/douyin/app/favorite/biz/repository"
	"github.com/crazyfrankie/douyin/app/favorite/biz/repository/dao"
	"github.com/crazyfrankie/douyin/app/favorite/biz/service"
	"github.com/crazyfrankie/douyin/app/favorite/ioc"
	"github.com/crazyfrankie/douyin/app/favorite/rpc"
	"github.com/crazyfrankie/douyin/app/favorite/rpc/client"
	"github.com/crazyfrankie/douyin/app/favorite/rpc/server"
)

// Injectors from wire.go:

func InitApp() *ioc.App {
	db := ioc.InitDB()
	favoriteDao := dao.NewFavoriteDao(db)
	favoriteRepo := repository.NewFavoriteRepo(favoriteDao)
	feedServiceClient := client.NewFeedClient()
	favoriteService := service.NewFavoriteService(favoriteRepo, feedServiceClient)
	favoriteServer := server.NewFavoriteServer(favoriteService)
	rpcServer := rpc.NewFavoriteRPCServer(favoriteServer)
	favoriteHandler := handler.NewFavoriteHandler(favoriteService)
	engine := ioc.InitWeb(favoriteHandler)
	app := &ioc.App{
		RPCServer:  rpcServer,
		HTTPServer: engine,
	}
	return app
}
