// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/crazyfrankie/douyin/bff/app/user/handler"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitGin() *gin.Engine {
	v := InitMiddlewares()
	userServiceClient := InitClient()
	handlerHandler := handler.NewHandler(userServiceClient)
	engine := InitWeb(v, handlerHandler)
	return engine
}
