// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/crazyfrankie/douyin/app/feed/biz/handler"
	"github.com/crazyfrankie/douyin/app/feed/biz/repository"
	"github.com/crazyfrankie/douyin/app/feed/biz/repository/dao"
	"github.com/crazyfrankie/douyin/app/feed/biz/service"
	"github.com/crazyfrankie/douyin/app/feed/ioc"
	"github.com/crazyfrankie/douyin/app/feed/rpc"
	"github.com/crazyfrankie/douyin/app/feed/rpc/client"
	"github.com/crazyfrankie/douyin/app/feed/rpc/server"
)

// Injectors from wire.go:

func InitApp() *ioc.App {
	db := ioc.InitDB()
	feedDao := dao.NewFeedDao(db)
	feedRepo := repository.NewFeedRepo(feedDao)
	userServiceClient := client.NewUserClient()
	feedService := service.NewFeedService(feedRepo, userServiceClient)
	videoServer := server.NewVideoServer(feedService)
	rpcServer := rpc.NewFeedRPCServer(videoServer)
	feedHandler := handler.NewFeedHandler(feedService)
	engine := ioc.InitWeb(feedHandler)
	app := &ioc.App{
		RPCServer:  rpcServer,
		HTTPServer: engine,
	}
	return app
}
