// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"fmt"
	"github.com/crazyfrankie/douyin/app/favorite/biz/handler"
	"github.com/crazyfrankie/douyin/app/favorite/biz/repository"
	"github.com/crazyfrankie/douyin/app/favorite/biz/repository/dao"
	"github.com/crazyfrankie/douyin/app/favorite/biz/service"
	"github.com/crazyfrankie/douyin/app/favorite/config"
	"github.com/crazyfrankie/douyin/app/favorite/rpc/server"
	"github.com/gin-gonic/gin"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
	"os"
)

// Injectors from wire.go:

func InitApp() *App {
	db := InitDB()
	favoriteDao := dao.NewFavoriteDao(db)
	favoriteRepo := repository.NewFavoriteRepo(favoriteDao)
	favoriteService := service.NewFavoriteService(favoriteRepo)
	favoriteHandler := handler.NewFavoriteHandler(favoriteService)
	engine := InitWeb(favoriteHandler)
	favoriteServer := server.NewFavoriteServer(favoriteService)
	app := &App{
		HTTPServer: engine,
		RPCServer:  favoriteServer,
	}
	return app
}

// wire.go:

func InitDB() *gorm.DB {
	dsn := fmt.Sprintf(config.GetConf().MySQL.DSN, os.Getenv("MYSQL_USER"), os.Getenv("MYSQL_PASSWORD"), os.Getenv("MYSQL_HOST"), os.Getenv("MYSQL_PORT"), os.Getenv("MYSQL_DB"))

	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{
		NamingStrategy: schema.NamingStrategy{
			SingularTable: true,
		},
	})
	if err != nil {
		panic(err)
	}

	return db
}

func InitWeb(favorite *handler.FavoriteHandler) *gin.Engine {
	engine := gin.Default()
	engine.Use(service.NewAuthBuilder().Auth())
	favorite.RegisterRoute(engine)

	return engine
}
