// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/crazyfrankie/douyin/app/favorite/biz/repository"
	"github.com/crazyfrankie/douyin/app/favorite/biz/repository/dao"
	"github.com/crazyfrankie/douyin/app/favorite/biz/rpc"
	"github.com/crazyfrankie/douyin/app/favorite/biz/rpc/client"
	"github.com/crazyfrankie/douyin/app/favorite/biz/rpc/server"
	"github.com/crazyfrankie/douyin/app/favorite/biz/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := InitDB()
	favoriteDao := dao.NewFavoriteDao(db)
	favoriteRepo := repository.NewFavoriteRepo(favoriteDao)
	feedServiceClient := client.InitFeedClient()
	favoriteService := service.NewFavoriteService(favoriteRepo, feedServiceClient)
	favoriteServer := server.NewFavoriteServer(favoriteService)
	rpcServer := rpc.NewFavoriteRPCServer(favoriteServer)
	app := &App{
		RPCServer: rpcServer,
	}
	return app
}
