// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/crazyfrankie/douyin/app/message/biz/repository"
	"github.com/crazyfrankie/douyin/app/message/biz/repository/dao"
	"github.com/crazyfrankie/douyin/app/message/biz/rpc"
	"github.com/crazyfrankie/douyin/app/message/biz/rpc/server"
	"github.com/crazyfrankie/douyin/app/message/biz/service"
	"github.com/crazyfrankie/douyin/app/message/ioc"
)

// Injectors from wire.go:

func InitApp() *ioc.App {
	db := ioc.InitDB()
	messageDao := dao.NewMessageDao(db)
	messageRepo := repository.NewMessageRepo(messageDao)
	messageService := service.NewMessageService(messageRepo)
	messageServer := server.NewMessageServer(messageService)
	rpcServer := rpc.NewMessageRPCServer(messageServer)
	app := &ioc.App{
		RPCServer: rpcServer,
	}
	return app
}
