// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: idl/douyin/sms.proto

package sms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Biz           string                 `protobuf:"bytes,1,opt,name=biz,proto3" json:"biz,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Numbers       []string               `protobuf:"bytes,3,rep,name=numbers,proto3" json:"numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsRequest) Reset() {
	*x = SendSmsRequest{}
	mi := &file_idl_douyin_sms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsRequest) ProtoMessage() {}

func (x *SendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_douyin_sms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsRequest.ProtoReflect.Descriptor instead.
func (*SendSmsRequest) Descriptor() ([]byte, []int) {
	return file_idl_douyin_sms_proto_rawDescGZIP(), []int{0}
}

func (x *SendSmsRequest) GetBiz() string {
	if x != nil {
		return x.Biz
	}
	return ""
}

func (x *SendSmsRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *SendSmsRequest) GetNumbers() []string {
	if x != nil {
		return x.Numbers
	}
	return nil
}

type SendSmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsResponse) Reset() {
	*x = SendSmsResponse{}
	mi := &file_idl_douyin_sms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsResponse) ProtoMessage() {}

func (x *SendSmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_douyin_sms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsResponse.ProtoReflect.Descriptor instead.
func (*SendSmsResponse) Descriptor() ([]byte, []int) {
	return file_idl_douyin_sms_proto_rawDescGZIP(), []int{1}
}

func (x *SendSmsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VerifySmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Biz           string                 `protobuf:"bytes,1,opt,name=biz,proto3" json:"biz,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySmsRequest) Reset() {
	*x = VerifySmsRequest{}
	mi := &file_idl_douyin_sms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySmsRequest) ProtoMessage() {}

func (x *VerifySmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_douyin_sms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySmsRequest.ProtoReflect.Descriptor instead.
func (*VerifySmsRequest) Descriptor() ([]byte, []int) {
	return file_idl_douyin_sms_proto_rawDescGZIP(), []int{2}
}

func (x *VerifySmsRequest) GetBiz() string {
	if x != nil {
		return x.Biz
	}
	return ""
}

func (x *VerifySmsRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *VerifySmsRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type VerifySmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySmsResponse) Reset() {
	*x = VerifySmsResponse{}
	mi := &file_idl_douyin_sms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySmsResponse) ProtoMessage() {}

func (x *VerifySmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_douyin_sms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySmsResponse.ProtoReflect.Descriptor instead.
func (*VerifySmsResponse) Descriptor() ([]byte, []int) {
	return file_idl_douyin_sms_proto_rawDescGZIP(), []int{3}
}

func (x *VerifySmsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_idl_douyin_sms_proto protoreflect.FileDescriptor

var file_idl_douyin_sms_proto_rawDesc = []byte{
	0x0a, 0x14, 0x69, 0x64, 0x6c, 0x2f, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2f, 0x73, 0x6d, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x6d, 0x73, 0x22, 0x50, 0x0a, 0x0e, 0x53,
	0x65, 0x6e, 0x64, 0x53, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x62, 0x69, 0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x7a, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x72, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x2b, 0x0a,
	0x0f, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x50, 0x0a, 0x10, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x53, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x62, 0x69, 0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x7a,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x2d, 0x0a, 0x11,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x7e, 0x0a, 0x0a, 0x53,
	0x6d, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x53, 0x65, 0x6e,
	0x64, 0x53, 0x6d, 0x73, 0x12, 0x13, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x53,
	0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x6d, 0x73, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3a, 0x0a, 0x09, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x6d, 0x73, 0x12, 0x15, 0x2e, 0x73,
	0x6d, 0x73, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x53, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2f,
	0x73, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_douyin_sms_proto_rawDescOnce sync.Once
	file_idl_douyin_sms_proto_rawDescData = file_idl_douyin_sms_proto_rawDesc
)

func file_idl_douyin_sms_proto_rawDescGZIP() []byte {
	file_idl_douyin_sms_proto_rawDescOnce.Do(func() {
		file_idl_douyin_sms_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_douyin_sms_proto_rawDescData)
	})
	return file_idl_douyin_sms_proto_rawDescData
}

var file_idl_douyin_sms_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_idl_douyin_sms_proto_goTypes = []any{
	(*SendSmsRequest)(nil),    // 0: sms.SendSmsRequest
	(*SendSmsResponse)(nil),   // 1: sms.SendSmsResponse
	(*VerifySmsRequest)(nil),  // 2: sms.VerifySmsRequest
	(*VerifySmsResponse)(nil), // 3: sms.VerifySmsResponse
}
var file_idl_douyin_sms_proto_depIdxs = []int32{
	0, // 0: sms.SmsService.SendSms:input_type -> sms.SendSmsRequest
	2, // 1: sms.SmsService.VerifySms:input_type -> sms.VerifySmsRequest
	1, // 2: sms.SmsService.SendSms:output_type -> sms.SendSmsResponse
	3, // 3: sms.SmsService.VerifySms:output_type -> sms.VerifySmsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_douyin_sms_proto_init() }
func file_idl_douyin_sms_proto_init() {
	if File_idl_douyin_sms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_douyin_sms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_douyin_sms_proto_goTypes,
		DependencyIndexes: file_idl_douyin_sms_proto_depIdxs,
		MessageInfos:      file_idl_douyin_sms_proto_msgTypes,
	}.Build()
	File_idl_douyin_sms_proto = out.File
	file_idl_douyin_sms_proto_rawDesc = nil
	file_idl_douyin_sms_proto_goTypes = nil
	file_idl_douyin_sms_proto_depIdxs = nil
}
