// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/crazyfrankie/douyin/app/publish/biz/repository"
	"github.com/crazyfrankie/douyin/app/publish/biz/repository/dao"
	"github.com/crazyfrankie/douyin/app/publish/biz/rpc"
	"github.com/crazyfrankie/douyin/app/publish/biz/rpc/client"
	"github.com/crazyfrankie/douyin/app/publish/biz/rpc/server"
	"github.com/crazyfrankie/douyin/app/publish/biz/service"
	"github.com/crazyfrankie/douyin/app/publish/ioc"
)

// Injectors from wire.go:

func InitApp() *ioc.App {
	db := ioc.InitDB()
	publishDao := dao.NewPublishDao(db)
	publishRepo := repository.NewPublishRepo(publishDao)
	favoriteServiceClient := client.InitFavoriteClient()
	publishService := service.NewPublishService(publishRepo, favoriteServiceClient)
	publishServer := server.NewPublishServer(publishService)
	rpcServer := rpc.NewPublishRPCServer(publishServer)
	app := &ioc.App{
		RPCServer: rpcServer,
	}
	return app
}
