// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/crazyfrankie/douyin/app/user/biz/handler"
	"github.com/crazyfrankie/douyin/app/user/biz/repository"
	"github.com/crazyfrankie/douyin/app/user/biz/repository/dao"
	"github.com/crazyfrankie/douyin/app/user/biz/service"
	"github.com/crazyfrankie/douyin/app/user/ioc"
	"github.com/crazyfrankie/douyin/app/user/rpc"
	"github.com/crazyfrankie/douyin/app/user/rpc/client"
	"github.com/crazyfrankie/douyin/app/user/rpc/server"
)

// Injectors from wire.go:

func InitApp() *ioc.App {
	db := ioc.InitDB()
	userDao := dao.NewUserDao(db)
	userRepo := repository.NewUserRepo(userDao)
	favoriteServiceClient := client.NewFavoriteClient()
	userService := service.NewUserService(userRepo, favoriteServiceClient)
	userServer := server.NewUserServer(userService)
	rpcServer := rpc.NewUserRPCServer(userServer)
	handlerHandler := handler.NewHandler(userService)
	engine := ioc.InitWeb(handlerHandler)
	app := &ioc.App{
		RPCServer:  rpcServer,
		HTTPServer: engine,
	}
	return app
}
