// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/crazyfrankie/douyin/app/user/biz/repository"
	"github.com/crazyfrankie/douyin/app/user/biz/repository/dao"
	"github.com/crazyfrankie/douyin/app/user/biz/rpc"
	"github.com/crazyfrankie/douyin/app/user/biz/rpc/client"
	"github.com/crazyfrankie/douyin/app/user/biz/rpc/server"
	"github.com/crazyfrankie/douyin/app/user/biz/service"
	"github.com/crazyfrankie/douyin/app/user/ioc"
)

// Injectors from wire.go:

func InitApp() *ioc.App {
	db := ioc.InitDB()
	userDao := dao.NewUserDao(db)
	userRepo := repository.NewUserRepo(userDao)
	favoriteServiceClient := client.NewFavoriteClient()
	publishServiceClient := client.NewPublishClient()
	userService := service.NewUserService(userRepo, favoriteServiceClient, publishServiceClient)
	userServer := server.NewUserServer(userService)
	rpcServer := rpc.NewUserRPCServer(userServer)
	app := &ioc.App{
		RPCServer: rpcServer,
	}
	return app
}
