// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/crazyfrankie/douyin/app/user/biz/repository"
	"github.com/crazyfrankie/douyin/app/user/biz/repository/dao"
	"github.com/crazyfrankie/douyin/app/user/biz/rpc"
	"github.com/crazyfrankie/douyin/app/user/biz/rpc/client"
	"github.com/crazyfrankie/douyin/app/user/biz/rpc/server"
	"github.com/crazyfrankie/douyin/app/user/biz/service"
)

// Injectors from wire.go:

func InitApp() *App {
	db := InitDB()
	userDao := dao.NewUserDao(db)
	userRepo := repository.NewUserRepo(userDao)
	favoriteServiceClient := client.InitFavoriteClient()
	publishServiceClient := client.InitPublishClient()
	relationServiceClient := client.InitRelationClient()
	userService := service.NewUserService(userRepo, favoriteServiceClient, publishServiceClient, relationServiceClient)
	userServer := server.NewUserServer(userService)
	rpcServer := rpc.NewUserRPCServer(userServer)
	app := &App{
		RPCServer: rpcServer,
	}
	return app
}
